---
abstract: 'Browse SQLite/MySQL/PostgreSQL databases and their tables interactively.'
author:
  - 'Matthaeus Kiem <cuer2s@gmail.com>'
build_requires:
  Test::More: '0'
configure_requires:
  ExtUtils::MakeMaker: '0'
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.98, CPAN::Meta::Converter version 2.142060'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: App-DBBrowser
no_index:
  directory:
    - t
    - inc
requires:
  Clone: '0'
  DBI: '0'
  Encode: '0'
  Encode::Locale: '0'
  File::Basename: '0'
  File::Find: '0'
  File::HomeDir: '0'
  File::Slurp: '0'
  File::Spec::Functions: '0'
  File::Temp: '0'
  FindBin: '0'
  Getopt::Long: '0'
  JSON: '0'
  List::MoreUtils: '0'
  List::Util: '0'
  Pod::Usage: '0'
  Scalar::Util: '0'
  Spreadsheet::Read: '0'
  Term::Choose: '1.116'
  Term::Choose::Util: '0.016'
  Term::ReadLine::Simple: '0'
  Term::TablePrint: '0.017'
  Text::CSV: '0'
  Text::LineFold: '0'
  Text::ParseWords: '0'
  perl: '5.010000'
resources:
  repository: https://github.com/kuerbis/App-DBBrowser.git
version: 0.046_01
